### ISSUE TITLE
Add node without any relationship

### ISSUE THREAD

**Issue by nawroth** [neo4j-contrib/neoclipse#62]
This is needed in order to create anything at all in a completely empty database.

I think this is a blocker for releasing Neoclipse with 2.0.0.

**Comment by manandbytes** [comment]
Could you provide steps to reproduce this issue?

**Comment by nawroth** [comment]
1. Create a new empty db.
2. Try creating a node in the graph view.

**Comment by peterneubauer** [comment]
I would love to work on this, but am not able ot set up neoclipse in Kepler to run the product, I can build with `mvn install` though.

@manandbytes is it possible to do a screencast or a skype meeting on setting up neoclipse 2.0 for development in Eclipse? Woudl be most appreciated!

**Comment by manandbytes** [comment]
Just tried these steps with Eclipse 3.8.2:
- install m2eclipse, http://www.eclipse.org/m2e/download/
- import Neoclipse as a Maven project
- close repository/ project (it will complain about missing path for Ant, could be safely ignored)
- open /default/default.target file
- press 'Set as Target Platform', it will download all required dependencies
- import neoclipse/osgi-bundle as a Maven project, it provides OSGIfied Neo4J
- rebuild (there should be no compilation errors)
- open neoclipse/repository/neoclipse.product file
- start Neoclipse via 'Lanuch an Eclipse application' button

@peterneubauer lets talk via skype, I've sent you an invitation.

**Comment by nawroth** [comment]
@manandbytes I tried that and all the warnings are gone, perfect!
Well, except I'm in the middle of some refactoring and need to wrap that up.
I've set out to resolve this issue if it doesn't take too long.
I'll add the instructions to the readme.

Thanks a lot!

**Comment by nawroth** [comment]
@peterneubauer I got this working in Eclipse 4.3.1 under Ubuntu.
For some reason the `org.neo4j.neoclipse.dependencies` module got set to use JavaSE-1.6.
I did "right click --> Maven ... --> Update Project" on it, and it changed to use 1.6 instead.
After that, the dependencies resolved correctly in `org.neo4j.neoclipse` module.

My fork is over here, not sure if it will work out well in the end:
https://github.com/nawroth/neoclipse
